version: "3.0"

services:
  php:
    image: sqstorage:master
    build:
      context: .
      dockerfile: Dockerfile.phpserver
    volumes:
      - "./:/app"
      - "./dba.php:/app/support/dba.php:rw"

  db:
    image: mariadb:${mariadb_tag}
    environment:
      - MYSQL_DATABASE=tlv
      - MYSQL_USER=tlvUser
      - MYSQL_PASSWORD=tlvUser
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  web:
    image: nginx:${nginx_tag}
    ports:
      - "1337:80"
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./:/app"

volumes:
  app:
